### ISSUE TITLE
License headers

### ISSUE THREAD

**Issue by hpvb** [electronicarts/EASTL#2]
Hi!

Thanks for taking the time to free this library. While I was idly browsing the sourcecode I noticed that the license headers on the files still say "// Copyright (c) Electronic Arts Inc. All rights reserved."

To be unambiguously useful it would help a lot of you could update the license headers to reflect the new distribution terms.

Thanks again,

**Comment by rparolin** [comment]
The intention was the LICENSE file in the root holds all the legal details.  I can confirm with our legal team internally but this was their recommendation.

**Comment by hpvb** [comment]
The primary reason for having license headers is that when a programmer doesn't need your entire program but only a couple of files and merges them in their own open source program. Once that happens there are suddenly files that carry an EA copyright notice without an accompanying license. A user of that program who then wants to use individual files from it won't know what license the files were under.

And of course there's a practical problem with automatic copyright enforcement programs that scan sourcecode and automatically send out cease and desist notices :)

**Comment by darkf** [comment]
The problem is that this makes it ambiguous what license it is actually under. The license headers for individual files would make it seem like it is not licensed for use by EA, but the root LICENSE makes it seem like it is under BSD-3.

I would *highly* suggest talking to legal again and then either removing the license headers from files or changing them to a BSD-3 preamble, that way there is no ambiguity.

**Comment by rparolin** [comment]
I'm talking with legal.  Stay tuned.

**Comment by rparolin** [comment]
Legal has informed us that, although the license terms might appear ambiguous if a single source code file was copied from this project, the project as a whole is explicitly licensed under the BSD 3-clause license.  Legal recommends that when copying a single source code file for another project, add the 3-clause license to the header so as to avoid any future ambiguity.

**Comment by hpvb** [comment]
I would agree with you if the whole project was under the three clause BSD license. But it's not. If you look at 3RDPARTYLICENSES.TXT it seems that not all files are covered purely by the license in LICENSE, furthermore there is a reference to "Copyright (c) 2009-2014 by the contributors listed in CREDITS.TXT" but it appears that CREDITS.TXT is missing.

Then there are several copyright notices in 3RDPARTYLICENSES.TXT that say can't be removed. So do we have to add all of those to single-file copies of a part of the EASTL?

Lastly there is a mention "Use of the software in this package is governed by the EA Development Software License, found in the accompanying file EA_DEV_SOFTWARE_LICENSE.txt." This file also appears to be missing.

The problem I'm trying to address is that for a third party it is basically impossible to determine what file requires what attribution if we copy a file from the EASTL into our own source trees, and distribute that under an open source license. But due to various missing bits of information it seems that even complying with the various attributions seems impossible due to missing information.

**Comment by rparolin** [comment]
I've addressed the issues above in the recent edit to the 3RDPARTYLICENSES.txt file.
- Added with CREDITS.TXT URL
- Removed EA_DEV_SOFTWARE_LICENSE.txt 

Finally, as far as the rest of the question – does everything have to be included when a single file is copied? – that depends on whether the code in that file depends on one of those licenses. So we can’t fully answer that for a single file.  They need to make that decision for themselves and put it in or not at their own risk.  What we know (and how we comply in EASTL) is that those licenses need to be included for the entire EASTL distribution, so that’s what we’ve done.

Hope that helps.

**Comment by hpvb** [comment]
Thanks for your answers!

**Comment by rparolin** [comment]
No problem.  Thank you.
