### ISSUE TITLE
Missing headers in EASTL

### ISSUE THREAD

**Issue by omersabary** [electronicarts/EASTL#217]
Hi, 
I saw there are many missing headers in EASTL compare to STL c++:
Execption, typeinfo, new, cassert, cctype. 
Am I missing something? I try to search them all over the source file and in you documentation. 

Thanks! 
Omer

**Comment by rparolin** [comment]
Some of those headers must be implemented by the toolchain so EASTL simply uses them (ie. RTTI typeinfo).  EASTL provides a replacement for standard library containers, allocators, and algorithms due to working around the std::allocator model.  You can read more of the details here:  http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2271.html
