### ISSUE TITLE
macro defining char8_t to char breaks valid code

### ISSUE THREAD

**Issue by xaxxon** [electronicarts/EASTL#233]
The macro in eabase.h breaks valid code:
https://github.com/electronicarts/EASTL/blob/master/test/packages/EABase/include/Common/EABase/eabase.h#L715

```
// this code is fine without the #define
#define char8_t char

enum char8_t : unsigned char {};
```

produces the error:
```

<source>:4:6: error: expected identifier or '{'

enum char8_t : unsigned char {};

     ^
```

https://godbolt.org/z/GjgPra

This example code comes from the popular c++ library {fmt}:

https://github.com/fmtlib/fmt/blob/master/include/fmt/format.h#L404

**Comment by tahonermann** [comment]
To be fair, `fmt` has no more right to the `char8_t` name than EASTL does, so when compiling for C++17 or earlier, this is just a typical name clash across projects.

However, [`char8_t` will be a keyword in C++20](http://wg21.link/p0482).  `fmt` is conditionally defining `char8_t` only if the corresponding feature test macro (`__cpp_char8_t`) is not defined; basically, @vitaut is preparing for C++20 by adding some compatibility features when `char8_t` support is not enabled in the compiler.

EASTL has at least two options for C++20:

1. Change the name of the `char8_t` macro.  This will break source compatibility, but not necessarily binary compatibility, for existing users.
2. Drop the `char8_t` macro in favor of the C++20 `char8_t` type.  This will break binary compatibility, but not necessarily source compatibility (I see EASTL defines `char8_t` as `char`, not as `unsigned char`, so this depends on whether existing code depends on `char8_t` being exactly `char` ).

**Comment by xaxxon** [comment]
What I saw was EASTL doing it globally, FMT doing it in a controlled
fashion... but since EASTL did it globally, FMT being a good citizen
doesn't matter.   Did I see it wrong?

**Comment by xaxxon** [comment]
fmt doesn't use a macro for what it does, though.

**Comment by tahonermann** [comment]
Right, neither EASTL nor fmt is doing anything wrong here.  The issue is that EASTL is defining a macro (as it is allowed to), but that macro is interfering with fmt's use of the same name given to that macro.  Neither project has more or less right to the `char8_t` name.  This is why I stated that this is just a typical name clash across projects.

Note that the comments around the EASTL definition of that macro suggest that the authors didn't actually want to use a macro; they did so (on Apple platforms) to work around a debugger limitation.

**Comment by vitaut** [comment]
Defining `char8_t` macro (or any unprefixed macro for that matter) is a horrible idea so it's better be fixed. That said I'll be OK to accept a PR with a workaround for this in {fmt}.

**Comment by xaxxon** [comment]
@tahonermann You're "allowed" to do all sorts of terrible things.   Making it sound like macros and highly localized `using` statements are the same is disingenuous.

**Comment by christinaa** [comment]
I recently submitted a PR into fmtlib that checks for this and avoids defining it if it's present (before `rC346892` char8_t required a compile-time flag to enable it, since then it's been enabled by default for C++2a).

https://github.com/fmtlib/fmt/pull/933/files

So with a recent enough fmtlib this should be fine if EASTL takes the same approach and uses a feature test, as neither will define it since the compiler would have. I could make a PR but I'm pretty sure the fix is obvious (though I'm not 100% sure regarding the issue with LLDB).

**Comment by rparolin** [comment]
@christinaa EABase ensures that char8_t (and similar types) are available; it currently does all the platform specific checks required but if we can add the new ISO standard feature defines and slowly remove the compiler specific checks that would be great.   If you want to send a PR that would be great.  I haven't done much work in adding the ISO feature defines yet.

**Comment by tahonermann** [comment]
EABase currently aliases `char8_t` to `char` by default.  Most other cases I've seen of roll-your-own-char8_t have aliased `unsigned char`.  I'm curious if there was a specific reason for defaulting to `char` over `unsigned char`.  Perhaps for compatibility with `u8` literals?

**Comment by rparolin** [comment]
@tahonermann not sure but I would presume  backwards compatiblilty.

**Comment by christinaa** [comment]
It's guarded by a feature check specific to C++20, so yes it's backwards compatible in a way that it will not attempt to define `char8_t` if the compiler explicitly defines the feature test that indicates it has native `char8_t` support. Anything that rolls its own `char8_t` without performing such a check is broken on Clang and will likely break on GCC soon as well (if it hasn't happen already) in C++2a mode (since it's a builtin type now).

As per specification:
```
char8_t - type for UTF-8 character representation, required to be large enough to represent 
any UTF-8 code unit (8 bits). It has the same size, signedness, and alignment as unsigned 
char (and. therefore, the same size and alignment as char and signed char), but is a 
distinct type
```

Pre-C++20, I'm not sure how implementations should handle it, since it's not defined by the specification I think it's down to library implementers since there's not much that can be done if two libraries decide to define it in an incompatible way besides talking to other library authors. While this ensures consistent C++20 support, in non-C++20 mode, things will work as they did before, so in that sense yes, it's perfectly backwards compatible.

**Comment by rparolin** [comment]
Just to be clear the backwards compatiblilty I was referring to was EABase defining char8_t as a signed char.
