### ISSUE TITLE
Make eastl::hash SFINAE-friendly

### ISSUE THREAD

**Issue by eugeneko** [electronicarts/EASTL#276]
In order to use SFINAE and partial template specialization `eastl::hash` has to have second defaulted template argument, e.g.
`template <typename T, typename = void> struct hash;`
so the user can do the tricks described at https://en.cppreference.com/w/cpp/types/enable_if to specialize hasher.

EASTL then would be able to drop this weird hack (if I don't misunderstand why it's needed)
https://github.com/electronicarts/EASTL/blob/2dc410a83119760bb8a85bd995717adf13490ded/include/EASTL/functional.h#L1011

Or maybe you know any reasons why it wasn't done before?..

**Comment by rokups** [comment]
From my experience implementing it - this is not a backwards-compatible change. All forward declarations of `hash` would need modifying, not specializations implementing hashing though. Implementation of this feature would allow to get rid of `Internal::EnableHashIf<T, is_enum_v<T>>` too (which does not work anyway due to default template having a body).

**Comment by rparolin** [comment]
Sorry for the delay.  I'd prefer to not diverge from the standard definition of std::hash as described.  As pointed out there are concerns about breaking existing code and the potential headaches in the future maintaining this divergence from the standard.

**Comment by eugeneko** [comment]
On the other hand, EASTL doesn't have to repeat all mistakes made by C++ Committee.
I hope they will change this part of the standard eventually.

As far as I understand, the compatibility issues may only occur when someone forward-declared `eastl::hash`. TBH I cannot imagine use case when you need forward declaration of `hash` in user code...
