### ISSUE TITLE
Windows 7/10 LNK2019 errors

### ISSUE THREAD

**Issue by IlyaStuurFedorov** [electronicarts/EASTL#289]
It seems that this haven't changed in a bit. Is there any updates on Win version? [Because it still has the same linking/allocator issues.](https://github.com/electronicarts/EASTL/issues/258)
https://i.imgur.com/zOZiCmI.png

**Comment by rparolin** [comment]
Not sure the question here.  The sample cpp file has been deleted.  The linker error you are refering to is the operator new signature that is required for EASTL because it allows injecting of additional debug information... and legacy concerns like alignment which have since been adopted into the standard.

That operator needs to be supplied by the app using EASTL.. the EASTL tests have an example of this.

**Comment by IlyaStuurFedorov** [comment]
Sorry for misunderstandment, but my problem is the same as OP, files that caused a bunch of troubles in past might've been deleted, but if I would not have opened this issue, I won't be able to figure out that I should look through tests in order to find a proper solution. My point is that this info needs to be added to CMake docs because this is not that much intuitive to people that are working with a third party STL replacement for the first time.

**Comment by rparolin** [comment]
https://github.com/electronicarts/EASTL/blob/master/doc/CMake/EASTL_Project_Integration.md#setting-up-your-code

I could add a link to this from the main readme.md.

**Comment by IlyaStuurFedorov** [comment]
That should do it, but also project integration needs to be updated with the additional missing unimplemented method as well. I would gladly help to assemble some basic CMake ready-to-deploy project if this is even considered, so people like me would have no problem configuring it for their own projects :)
