### ISSUE TITLE
Build issue | Xcode 7.2 Apple LLVM version 7.0.2 (clang-700.1.81) Target: x86_64-apple-darwin14.5.0

### ISSUE THREAD

**Issue by nyotis** [electronicarts/EASTL#3]
CMake generates files properly, but none of the header files is detected at the very start of the of the config.h so i need to point out to the directory manually

```
#ifndef EASTL_EABASE_DISABLED
    #include <EABase/eabase.h>
#endif
    #include <EABase/eahave.h>
```

**Comment by nyotis** [comment]
unless if the Clang formatting relates to an LLVM source from source?

**Comment by rparolin** [comment]
OSX is tested internally but not yet using CMake.  I'm trying to get the project up on Travis-CI now that the repo is public.

**Comment by shadowmint** [comment]
If you use this CMakeLists.txt that references the include directories it'll try to compile:

```
#-------------------------------------------------------------------------------------------
# Library definition
#-------------------------------------------------------------------------------------------
file(GLOB EASTL_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/source/*.cpp")
add_library(EASTL ${EASTL_SOURCES})

#-------------------------------------------------------------------------------------------
# Include dirs
#-------------------------------------------------------------------------------------------
target_include_directories(EASTL PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
target_include_directories(EASTL PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/test/packages/EABase/include/Common)
target_link_libraries(EASTL EABase)
```

...but it'll fail with errors like:

```
In file included from /Users/doug/dev/cpp/EASTL/source/allocator_eastl.cpp:6:
In file included from /Users/doug/dev/cpp/EASTL/include/EASTL/internal/config.h:61:
/Users/doug/dev/cpp/EASTL/test/packages/EABase/include/Common/EABase/eabase.h:732:20: error: typedef redefinition with different types ('uint16_t' (aka 'unsigned short') vs 'char16_t')
                typedef uint16_t char16_t;
                                 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:234:20: note: previous definition is here
typedef __char16_t char16_t;
                   ^
In file included from /Users/doug/dev/cpp/EASTL/source/allocator_eastl.cpp:6:
In file included from /Users/doug/dev/cpp/EASTL/include/EASTL/internal/config.h:61:
/Users/doug/dev/cpp/EASTL/test/packages/EABase/include/Common/EABase/eabase.h:733:20: error: typedef redefinition with different types ('wchar_t' vs 'char32_t')
                typedef wchar_t  char32_t;
                                 ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__config:235:20: note: previous definition is here
typedef __char32_t char32_t;
``

and so on and so on.

Seems like OSX support is still quite distant. 

On the bright side, it compiles on linux without any trouble, so there's something.

**Comment by nyotis** [comment]
OK cheers. Will try to compile based on LLVM from source

**Comment by Nuclearfossil** [comment]
This is also happening using CMake + Visual Studio 2015 (Win64)

**Comment by nyotis** [comment]
OK, so I am not closing this. 
Nucleafossil can you flag this as a separate Win issue?

**Comment by nyotis** [comment]
thanks @rparolin, let us know if u need any help w/ Travis CI

**Comment by Nuclearfossil** [comment]
Absolutely.  I'll also create a PR once I have it fixed locally.

**Comment by rparolin** [comment]
@nyotis Thanks, help would be great!  Right now the travis-ci cmake 2.8.7 version is causing issues since the requirement is 3.4.  The can probably be relaxed by since EABase is a header only library I know the required features aren't in 2.8.7.

**Comment by rparolin** [comment]
I'd like to get travis up and running before accepting significant pull requests.  Luckily the majority have been documentation related.

**Comment by ppedriana** [comment]
Looks like EABase is mis-detecting how to deal with char16_t for that particular configuration. This shouldn't be related to EASTL itself.

**Comment by shadowmint** [comment]
Idly EABase is currently a hard dependency for EASTL because, even if you define  EASTL_EABASE_DISABLED there are perhaps 50 different places it's referenced or included, like:

https://github.com/electronicarts/EASTL/blob/master/include/EASTL/internal/config.h#L63

https://github.com/electronicarts/EASTL/blob/master/include/EASTL/internal/fixed_pool.h#L22

etc.

I don't really know any of the background about the difference between EASTL and EABase, but having a broken or missing EABase appears to (currently) make EASTL unusable.

**Comment by ppedriana** [comment]
EASTL depends on a number of parts of EABase to get base information about the compiler environment. It appears that something needs to be fixed in EABase for that particular iteration of XCode. I left EA 1.5 years ago, but EABase was developed and used heavily on OS X/XCode at the time, so this problem is likely a minor thing due to some compiler change.

**Comment by rparolin** [comment]
OSX builds are up on Travis-CI

**Comment by shadowmint** [comment]
Just running cmake won't work. 

The command to build the tests folder is:

    cmake -Bbuild -Htest && cmake --build build

NB. `-B`, `-H` amd `--build` are all undocumented cmake features; respectively they specify the build directory, set the home directory to `EASTL/test` and execute the 'per platform build instruction' on the newly created build folder.

The equivalent (non-obscure) result is achieved with:

    mkdir build
    cd build
    cmake ../test
    make

...ie. Yay! It works... but since there are no hints on how to build it, it sucks somewhat that the CI uses undocumented features; I leave this here to other people who find that the build fails with errors like this:

```
EASTL/test/packages/EABase/include/Common/EABase/nullptr.h:28:9: note: candidate found by name lookup is 'std::nullptr_t'
                class nullptr_t
```

(that means you just tried to run `cmake .. && make` which wont work).

The link to the OSX CI is here:
https://travis-ci.org/electronicarts/EASTL/jobs/109114858

**Comment by rparolin** [comment]
@shadowmint I've added more detail on how to build here as feedback came in:
https://github.com/electronicarts/EASTL/blob/master/CONTRIBUTING.md

**Comment by bobsummerwill** [comment]
Hello there, @ppedriana!   Great to see you involved with EASTL again :-)
http://bobsummerwill.com/2016/02/10/eastl-has-been-open-sourced-by-ea-for-real/

**Comment by nyotis** [comment]
ALL_BUILD succeeds with CMake GUI
