### ISSUE TITLE
Submodule hell - not the way they're meant to work

### ISSUE THREAD

**Issue by IanMDay** [electronicarts/EASTL#302]
Hi,

I'm not sure who's idea it was to switch to submodules. That in itself is not a huge problem, a little annoying maybe, but ok, fair enough, its your project. But to make them interdependent so that `--recursive` is effectively broken? Its now very difficult (read: impractical) to keep up-to-date with the latest versions without hacking around, creating an independent folder and committing that to a local repository without the submodules. It just takes someone who already has other submodules in their project, such as protobuf for example, that has its own submodules so that they require the use of `--recursive` for a successful clone.

Please reconsider this layout. I'm a long time user of EASTL and I'm glad its still being maintained and is as great as ever, but this change is going to be an ongoing issue to keep up-to-date.

**Comment by rparolin** [comment]
The context for this decision was to manage our internal technology dependencies (EABase, EATest, etc) as separate git repos.  Plus in the future, EA would like to open source technology and having separate repos would allow us to explicitly depend on this infrastructure technology.

Knowing that, I couldn't see a better solution for how to achieve that.  There was suggestions for using an external package manager but I was resisting that idea because everyone has a personal preference and I didn't want to introduce another technology into the mix.  

Do you have a suggestion on how the submodules could be improved or how it can be achieved with a different technique?

**Comment by IanMDay** [comment]
Well the real issue is the test/packages submodules also depend on EASTL itself. As your guidelines say, trying to clone recursively from that will just eat up the available disk space.

My alternative would be to avoid the cyclic dependency and instead have a test stub that depends on all of the submodules, but nothing depends on it in return.

**Comment by rparolin** [comment]
Agreed.  This is an unfortunate knock-on from EATest using the technology its testing.  I'm not sure I understand what you mean by a test stub?  Can you provide more details?  We don't have any immediate plans to migrate our unit tests to another testing technology.  We have been using gtest in other areas with success (which would break the cycle) and we've had that discussion to potentially migrate but we haven't made any decisions yet.

Apologies.  It's not a great answer.

**Comment by IanMDay** [comment]
No, I'm not talking about changing your test platform. I'm only concerned with the git setup.

The basic fact is, EASTL is the library and should be common requirement of all the others that depend on it. Since there are multiple sub-modules, each one including EASTL as a sub-module would not work. So, an alternative is to demote EASTL to a sub-module and create an EASTLRoot that includes each of the others. Remove the sub-module requirements from all the rest and leave that all to EASTLRoot. Add a CMakeLists.txt to EASTLRoot and with a little magic, the rest should be fairly transparent to the user. Ultimately we don't care which folder things are in, if they're in a sub-module or not does not matter. CMake will sort it all out and as long as the various libraries retain their current name, no-one will care.

I would also take a look at the others. For example, EABase, which is effectively just compiler configuration and some cross platform fluff. I feel that should only be required by EASTL itself. It can can use `target_include_directories` so that the EABase include folder is passed on to anything that uses EASTL. I expect the same can be said for EAAssert at the least. And as a side-note, I never felt that the `test` folder was a good place for these to live since they're always required to build the core library :)

Do you have a specific requirement that means you need be able to clone EATest as the root clone point? Or EAMain? etc.

**Comment by rparolin** [comment]
Agreed the packages being placed in the test folder isn't great.  I will move them out to a "dependencies" or "external" folder in the future. 

If I'm understanding you correctly, I don't want to separate the EASTL library code from the test code.   These libraries in git-submodules are core infrastructure libraries for all EA code and any potential future open source projects would need to depend on them.  I'm trying to keep the structure as close to what we have internally to enable (as easily as I can) future code to be open sourced.

**Comment by rparolin** [comment]
I'm going to close this issue. We can reopen the discussion if there is a proposed change to fits our constraints.  Thanks.

**Comment by jvetter1** [comment]
Why did this get closed? nothing was resolved and you closed mine #304 as duplicate

We have know way to get a working release from git or from your releases that includes the submodules. Are you saying that is intended and this isn't a bug?

**Comment by IanMDay** [comment]
I agree. Some thought is needed here but I do not have personal knowledge of how the internal EA code depends on this so I'm not really in a good position to supply a definitive solution. How does EA include EASTL and its new submodules without --recursive?

I don't feel that submodules was the answer here. If you clone EASTL, you will always need most of the other parts. Is that not true of anything that requires EASTL? I don't really understand the benefit gained here. I understand some granularity is wanted, but I feel this is a self-contained library with its supporting code.

**Comment by rparolin** [comment]
We don't use git internally however the dependent libraries are separate repos.  We wanted to replicate that externally so that it would.enable us to publish more code.in the future.  Also this allows us to manage the changes to dependencies separate from EASTL publically.  I don't see how to achieve that without submodules.  I'd be interested in alternatives if any exist.

**Comment by IanMDay** [comment]
Are they required for EASTL though? All of the submodules depend directly on EASTL. In my eyes, this makes them too inter-related for this submodule layout since none of them will function without the others.

But, if you're committed to this approach, then take boost as an example. There's a root module that includes all other submodules. Each of those submodules does have code dependencies with other modules, but they do not include their own submodules. They just depend on the root repository to do that.

**Comment by rparolin** [comment]
The dependencies are required for the EASTL tests.  For the EASTL library, only EABase is a required dependency.  I'll take a look at the boost as an example to see if I can improve the workflow.

**Comment by AlexRamallo** [comment]
I don't understand why EATest needs to have any submodules at all. If the idea is to use EATest as a central testing repo which tests everything at once, there are better ways to do that. A problem with doing it like this (with submodules) is that you'll need to remember to pull each submodule individually before each test, because submodules in git refer to a specific commit rather than the repository as a whole. You'll also likely want to commit those changes to the submodules so that anyone who pulls EATest will have the latest versions, meaning that the commit history for EATest will quickly become polluted with endless submodule updates. That's not very useful IMO.

If you remove all of the submodules from EATest, that will solve this recursive cloning problem. EASTL, EABase, EAStdC, etc can still keep EATest as a submodule so you can run tests locally within each repo.

If you want to do central testing, then you can do that in a new dedicated repo that has EATest, EASTL, EABase, etc. as submodules. Or better yet, EATest is the only submodule and the other repos are downloaded via a shell script or package manager.

**Comment by xgalaxy** [comment]
> Knowing that, I couldn't see a better solution for how to achieve that

IMO, this would be better achieved by using CMake built in functionality such:
- https://cmake.org/cmake/help/v3.11/module/ExternalProject.html

Or even better:
- https://cmake.org/cmake/help/v3.11/module/FetchContent.html

`FetchContent` is a bit better because it allows you to configure the dependencies at configure time rather than at build time.

**Comment by IanMDay** [comment]
Agreed. This would be a perfectly suitable alternative.

**Comment by DBJDBJ** [comment]
It is now 2020 Sep. And I could not just git clone EASTL.

The problem RP has in this "decision has been made" part ... _That might be the wrong decision_. Technology is not the problem here but the "decision makers".  If RP would be a "decision maker" he would do this much better probably.

How do I start using EASTL 2020?

**Comment by DBJDBJ** [comment]
I just had to install vcpkg ( which is in the "you be the guinea pig" state ) to get to ESTL source. And then, I locally copied the includes and sources to another local project folder. Builds and runs.

Then from that, I will have to make my own git repo to be able to push it back to github ... 

And, right now I am having the WTF epiphany realizing the EASTL  allocator jamboree ...  No surrender?
