### ISSUE TITLE
How to implement aligned delete?

### ISSUE THREAD

**Issue by ResolumeMenno** [electronicarts/EASTL#314]
I'm trying to use an eastl::fixed_hash_map with overflow enabled. This type requires the void* operator new[]( size_t, size_t, size_t, const char*, int, unsigned, const char*, int ) function to be implemented by the application, but i'm having a hard time figuring out how i'm supposed to implement it.

My problem comes from choosing the backing allocation function. I could choose windows' [_aligned_malloc](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/aligned-malloc?view=vs-2019) but then the returned pointer is supposed to be freed using [_aligned_free](_aligned_free).
Looking at eastl::allocator::deallocate it seems to not use any overloaded delete operator. That means if i were to override the global delete operator i would also need to override the global new operator to make sure everything is allocated aligned?

Alternatively i could try to mimic EASTLTestAllocator.cpp's delete[] implementation, but then i would need to have an allocator on which i could call IsConstructed. Is there something available in the eastl i'm overlooking or are we supposed to roll our own general allocator if we want to use eastl containers that use aligned allocations?

**Comment by rparolin** [comment]
If you are just trying to route to the system allocator you don't need an IsConstructed call.  That is only required because we have global instance of our custom allocator so we can't allocate from it until its been constructed via static init.  That's been changed in dev and will be released in a future version to use a Meyers singleton to construct on initial allocation request.

You can probably get away with what the EASTL unit test do:

		void* EASTLAlignedAlloc(size_t size, size_t alignment)
		{
		#ifdef EA_PLATFORM_MICROSOFT
			return _aligned_malloc(size, alignment);
		#else
			void *p = nullptr;
			alignment = alignment < sizeof( void *) ? sizeof( void *) : alignment;
			posix_memalign(&p, alignment, size);
			return p;
		#endif
		}

		void EASTLAlignedFree(void* p)
		{
		#ifdef EA_PLATFORM_MICROSOFT
			_aligned_free(p);
		#else
			free(p);
		#endif
		}
