### ISSUE TITLE
Why is _CHAR16T defined in CMake files?

### ISSUE THREAD

**Issue by pzychotic** [electronicarts/EASTL#33]
Why is _CHAR16T defined in pretty much every CMakelist.txt?

The comment in eabase.h:629 suggests that this is only needed for VS2010 and if that is the case, it should be set in the CMake files only when building with VS2010.

On the other hand this macro is already defined in eabase.h:721 for VS2010+. I haven't tried to trace all the platform detection code that leads to this point, but it might suggest that the define in the CMake files is unnecessary?

Any clarifications on this?

**Comment by rparolin** [comment]
MSVC didn't implement char16_t/char32_t until VS2015.
https://msdn.microsoft.com/en-us/library/hh567368.aspx?f=255&MSPPError=-2147217396

Defining _CHAR16T prevents yvals.h from defining the char16_t/char32_t and allows EABase to define them.  Its obviously not ideal as EABase will define them as a typedef instead of as unique types defined by the compiler.  Ideally, this would be enabled for versions lower than VS2015 only.
