### ISSUE TITLE
basic_string<wchar_t, Allocator>::insert(const_iterator p, const value_type* pBegin, const value_type* pEnd) crashes in Visual Studio >=16.6.2 x64 Release builds

### ISSUE THREAD

**Issue by TheAnswer** [electronicarts/EASTL#381]
basic_string<wchar_t, Allocator>::insert(const_iterator p, const value_type* pBegin, const value_type* pEnd)

https://gist.github.com/TheAnswer/f86c01b0d3f3e59884a72427fa2369c3

Compile flags: // /GS- /W4 /Gy /Zc:wchar_t /I"C:\Users\TheAnswer\.conan\data\eastl\3.16.07\_\_\package\1d008178a12a8c613a7091c49126a86946c23522\include" /I"C:\Users\TheAnswer\.conan\data\eabase\2.09.05\_\_\package\5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9\include\Common" /Zi /Gm- /Ox /Ob2 /sdl /Fd"x64\Release\vc142.pdb" /Zc:inline /fp:fast /D "NDEBUG" /D "_CONSOLE" /D "PLATFORM_WINDOWS=1" /D "PROFILER_NOPROFILER=1" /D "PROFILER_TELEMETRY=0" /D "PROFILER_TRACY=0" /D "WIN64" /D "_HAS_EXCEPTIONS=0" /D "_LIB" /D "_SILENCE_ALL_CXX17_DEPRECATION_WARNINGS=1" /D "_UNICODE" /D "UNICODE" /fp:except- /errorReport:prompt /GF /WX- /Zc:forScope /GR- /Gd /Oy- /Oi /MD /openmp- /std:c++17 /FC /Fa"x64\Release\" /nologo /Fo"x64\Release\" /Ot /Fp"x64\Release\EASTLTest2.pch" /diagnostics:column 

basic_string with wchar_t miscompiles in visual studio >= 16.6.2 release x64 builds on windows leading to heap out of bounds writes.

Specifically these lines in the mentioned eastl method:

                	const bool bCapacityIsSufficient = (internalLayout().GetRemainingCapacity() >= n);
			const bool bSourceIsFromSelf = ((pEnd >= internalLayout().BeginPtr()) && (pBegin <= internalLayout().EndPtr()));

bCapacityIsSufficient is set to true when it should not.

![image (3)](https://user-images.githubusercontent.com/557049/86511009-62c5f880-bdf5-11ea-9732-5956cdcb4bce.png)

Tested under VS 16.6.2 and 16.6.3

**Comment by TheAnswer** [comment]
Changing the call order of those 2 methods "fixes" the misscompile

**Comment by virt00l** [comment]
Hm, it's seems that it happens suspiciously close with crash on GCC 9/linux, that I fixed in https://github.com/electronicarts/EASTL/pull/380 (different env, but almost same place in code). Could you may be check this PR in your environment?

**Comment by MaxEWinkler** [comment]
My assembly of GetHeapCapacity() becomes:
`mov         r14,7FFFFFFFFFFFFFFFh 
 and         rdx,r14`
since the compiler should be able to constant fold the ~kHeapMask.
The assembly that you are showing (rdx + rdx) >> 1 is correct to compute the current capacity though a little convoluted at first glance. Let's use uint32_t for this example.
heap.mnCapacity == 0x80000001, the capacity is 1 with the heap bit set.
Our computation becomes:  
(((2^31 + 1) + (2^32 + 1)) mod (2^32)) >> 1
((4294967298) mod (2^32)) >> 1
2 >> 1
1 which is the correct heap capacity. Let's try some edge cases.
heap.mnCapacity == 0x800000000 becomes 0 as expected.
heap.mnCapacity == 0xFFFFFFFFFF becomes 2147483647 or 0x7FFFFFFFF as expected.

I don't think the issue lies in the computation of GetHeapCapacity().
Can you disasm of the whole function if possible, I'm curious of the return value of GetRemainingCapacity() { BeginPtr() + GetHeapCapacity() - BeginPtr() + GetHeapSize() } and the cmp with n.
Also can you try with /O2 instead of /Ox optimization level as another data point.
Thanks :).

**Comment by TheAnswer** [comment]
> I don't think the issue lies in the computation of GetHeapCapacity().

It is not, its where that calculation is placed in the resulting assembly that is the problem

> Also can you try with /O2 instead of /Ox optimization level as another data point.

Anything besides /Od (optimizations disabled) causes the misscompile

> Could you may be check this PR in your environment?

I will have some more time this week to check.

**Comment by TheAnswer** [comment]
The full assembly of the misscompiled method can be found here:

https://gist.github.com/TheAnswer/bd14f43520411bcd7a1d35fc1f09ec99

The misscompile seems to happen around .text:0000000140001707 where the clearance of the highest bit from capacity is in the wrong place? Needs more RE work though

**Comment by TheAnswer** [comment]
This is now fixed in VS 2022 (17.1.1)
