### ISSUE TITLE
fixed_vector<>::full() returns true when empty

### ISSUE THREAD

**Issue by PeterDalton** [electronicarts/EASTL#88]
The following code fails:
`eastl::fixed_vector<int,5> myVector;`
`if (myVector.full())`
`{`
`  FAILURE`
`}`

This seems incorrect.  Am I expected to also check that !myVector.empty().  The problem is that

`((void*)mpBegin != (void*)mBuffer.buffer)`

because mpBegin == nullptr

Thoughts?

**Comment by rparolin** [comment]
`bool      full() const;                 // Returns true if the fixed space has been fully allocated. Note that if overflow is enabled, the container size can be greater than nodeCount but full() could return true because the fixed space may have a recently freed slot.` 

Are you in the situation where the fixed_vector has overflowed?  I guess its a design question on what the expected behavior of fixed_vector::full should return after the container is in overflow mode.  The source comments indicate that once the container has overflowed its considered full even if the size is within the range.

```
 // If size >= capacity, then we are definitely full.
        // Also, if our size is smaller but we've switched away from mBuffer due to a previous overflow, then we are considered full.
```

**Comment by PeterDalton** [comment]
You are correct concerning the overflow.  I'm on board with the current design decisions when dealing with overflow handling.  I'm considering this issue resolved, thanks for your time.

**Comment by rparolin** [comment]
Thanks for submitting the issue.
